FROM balenalib/%%BALENA_ARCH%%-ubuntu:focal-build-20220320 as build

ARG K3S_VERSION=v1.27.16%2Bk3s1

COPY install-k3s.sh /docker/install-k3s.sh
RUN /docker/install-k3s.sh %%BALENA_ARCH%%

FROM balenalib/%%BALENA_ARCH%%-ubuntu:focal-run-20220320 as run

COPY --from=build /usr/local/bin/k3s /usr/local/bin/k3s

COPY start.sh /docker/start.sh
CMD ["/docker/start.sh"]
