[tool.poetry]
name = "chi-edge-workers"
version = "0.1.0"
description = ""
authors = ["Chameleon Team <contact@chameleoncloud.org>"]
license = "MIT"
packages = [
    { include = "scripts" }
]

[tool.poetry.dependencies]
python = "^3.8"
balena-sdk = "^11.4.0"
click = "^8.1.3"
rich = "^12.4.1"

[tool.poetry.dev-dependencies]
black = "^22.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
canary = "scripts.canary:main"
