apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvidia-device-plugin
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: nvidia-device-plugin
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: nvidia-device-plugin
    spec:
      priorityClassName: system-node-critical
      nodeSelector:
        nvidia-device-plugin/enabled: "true"
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
      containers:
        - name: nvidia-device-plugin-ctr
          image: nvcr.io/nvidia/k8s-device-plugin:v0.19.0
          env:
            - name: DEVICE_LIST_STRATEGY
              value: "envvar"
            - name: DEVICE_DISCOVERY_STRATEGY
              value: "tegra"
            - name: FAIL_ON_INIT_ERROR
              value: "false"
            - name: NVIDIA_VISIBLE_DEVICES
              value: "all"
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: "compute,utility"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: device-plugin
              mountPath: /var/lib/kubelet/device-plugins
            - name: cdi
              mountPath: /var/run/cdi
            - name: nv-tegra-release
              mountPath: /etc/nv_tegra_release
              readOnly: true
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: cdi
          hostPath:
            path: /var/run/cdi
            type: DirectoryOrCreate
        - name: nv-tegra-release
          hostPath:
            path: /etc/nv_tegra_release
