apiVersion: v1
kind: Pod
metadata:
  name: test-gpu
spec:
  restartPolicy: Never
  nodeSelector:
    kubernetes.io/hostname: iot-orin-nano-01
  containers:
    - name: test-gpu
      image: docker.io/shermanm/gpu-burn:latest
      command: ["ldd","sm87/gpu_burn"]
      resources:
        limits:
          nvidia.com/gpu: "1"
