apiVersion: v1
kind: Pod
metadata:
  name: test-gpu
spec:
  restartPolicy: Never
  nodeSelector:
    kubernetes.io/hostname: iot-orin-nano-01
    # kubernetes.io/hostname: iot-xavier-nx-01
  containers:
    - name: test-gpu
      image: ubuntu:22.04
      imagePullPolicy: Always
      command: ["tegrastats"]
      resources:
        limits:
          nvidia.com/gpu: "1"
