FROM balenalib/%%BALENA_ARCH%%-ubuntu:jammy-build-20250521 as build

ARG K3S_VERSION=v1.23.17%2Bk3s1

COPY install-k3s.sh /docker/install-k3s.sh
RUN /docker/install-k3s.sh %%BALENA_ARCH%%

FROM balenalib/%%BALENA_ARCH%%-ubuntu:jammy-run-20250521 as run

COPY --from=build /usr/local/bin/k3s /usr/local/bin/k3s

COPY start.sh /docker/start.sh
CMD ["/docker/start.sh"]
