FROM ghcr.io/chameleoncloud/jetson-infra:t210-32.7

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    iproute2 \
    runc \
    && rm -rf /var/lib/apt/lists/*


ARG K3S_VERSION=v1.29.15%2Bk3s1

COPY install-k3s.sh /docker/install-k3s.sh
RUN /docker/install-k3s.sh "aarch64"

ENV UDEV=on

COPY start.sh /docker/start.sh
CMD ["/docker/start.sh", "--default-runtime=nvidia"]
