ARG K3S_TAG=v1.29.15-k3s1
FROM rancher/k3s:${K3S_TAG} as k3s

# Start from "scratch" to remove all preconfigured env vars and volumes
FROM scratch

COPY --from=k3s / /

# k3s places a bunch of iptables related things in /bin/aux
ENV PATH="$PATH:/bin/aux"

COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
