ARG BASE_IMAGE=ghcr.io/chameleoncloud/chi-edge-workers/jetson-base:t210-r32.7
ARG K3S_TAG=v1.29.15-k3s1

FROM rancher/k3s:${K3S_TAG} AS k3s

FROM ${BASE_IMAGE}

COPY --from=k3s /bin/k3s /usr/local/bin/k3s

ENV UDEV=on

COPY start.sh /docker/start.sh
CMD ["/docker/start.sh"]
