FROM python:3.12-alpine

RUN apk add wireguard-tools

WORKDIR /opt/chi-edge/coordinator
COPY coordinator/ /opt/chi-edge/coordinator/
RUN pip install .

COPY fleet/coordinator/entrypoint.sh .
ENTRYPOINT ["./entrypoint.sh"]
