ARG BASE_IMAGE=balenalib/jetson-xavier-nx-devkit-emmc-ubuntu

FROM ${BASE_IMAGE}:bionic-build-20220320 as k3s-build

ARG K3S_VERSION=v1.22.5%2Bk3s1

COPY install-k3s.sh /docker/install-k3s.sh
RUN /docker/install-k3s.sh "aarch64"

FROM ${BASE_IMAGE}:bionic-run-20220320 as run
RUN install_packages \
    binutils \
    lbzip2 \
    libegl1 \
    python3 \
    tar \
    wget \
    xz-utils

# BSP binaries for L4T 32.7.3
RUN install_packages \
    nvidia-container-runtime

COPY install_tegra.sh /docker/install_tegra.sh
RUN /docker/install_tegra.sh

COPY --from=k3s-build /usr/local/bin/k3s /usr/local/bin/k3s

# Override default containerd config.toml with template file. This is copied into the config volume by start.sh
# Copied from https://github.com/k3s-io/k3s/blob/master/pkg/agent/templates/templates_linux.go
COPY config.toml.tmpl /docker/config.toml.tmpl

COPY start.sh /docker/start.sh
CMD ["/docker/start.sh"]
