FROM ubuntu:24.04

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        python3 \
        python3-pip \
        wireguard-tools \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/chi-edge/coordinator
COPY chi-edge-coordinator/ /opt/chi-edge/coordinator/chi-edge-coordinator/
RUN pip install --break-system-packages ./chi-edge-coordinator

COPY entrypoint.sh .
ENTRYPOINT ["./entrypoint.sh"]
