FROM python:3.12-alpine3.22

RUN apk add wireguard-tools

WORKDIR /opt/chi-edge/coordinator
COPY chi-edge-coordinator/ /opt/chi-edge/coordinator/chi-edge-coordinator/
RUN pip install ./chi-edge-coordinator

COPY entrypoint.sh .
ENTRYPOINT ["./entrypoint.sh"]
