name: Jetson Base Images

on:
  push:
    branches: [main]
    paths:
      - 'images/jetson-base/**'
  pull_request:
    paths:
      - 'images/jetson-base/**'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io/chameleoncloud/chi-edge-workers

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - soc: t210
            l4t: r32.7
            ubuntu: "18.04"
            cuda: "10.2"
          - soc: t194
            l4t: r32.7
            ubuntu: "18.04"
            cuda: "10.2"
          - soc: t234
            l4t: r36.4
            ubuntu: "22.04"
            cuda: "12.6"
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ env.REGISTRY }}/jetson-base
          tags: |
            type=raw,value=${{ matrix.soc }}-${{ matrix.l4t }}
            type=sha,prefix=${{ matrix.soc }}-${{ matrix.l4t }}-
            type=raw,value=${{ matrix.soc }}-${{ matrix.l4t }}-{{date 'YYYYMMDD'}}
      - uses: docker/build-push-action@v6
        with:
          context: ./images/jetson-base
          build-args: |
            SOC=${{ matrix.soc }}
            L4T_VERSION=${{ matrix.l4t }}
            UBUNTU=${{ matrix.ubuntu }}
            CUDA_VERSION=${{ matrix.cuda }}
          target: base
          platforms: linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
