name: PR Build

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches: [main]
    paths-ignore:
      - 'images/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: balena-io/deploy-to-balena-action@master
        id: deploy
        if: github.event.action != 'closed'
        with:
          balena_token: ${{ secrets.BALENA_API_TOKEN }}
          fleet: chameleon/chi-edge-workers

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'

      - name: install canary tool
        run: pip install .

      - name: Deploy to canary devices
        if: github.event.action != 'closed'
        env:
          BALENA_TOKEN: ${{ secrets.BALENA_API_TOKEN }}
        run: canary deploy ${{ steps.deploy.outputs.release_id }}

      - name: Rollback canary devices
        if: github.event.action == 'closed'
        env:
          BALENA_TOKEN: ${{ secrets.BALENA_API_TOKEN }}
        run: canary rollback
